version: '3.8'

services:
  db:
    image: postgres:13
    container_name: 'flipper-db'
    environment:
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'flipper-backend'
    environment:
      DATABASE_HOST: '${DATABASE_HOST}'
      DATABASE_PORT: '${DATABASE_PORT}'
      DATABASE_USER: '${DATABASE_USER}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      DATABASE_NAME: '${DATABASE_NAME}'
    ports:
      - '${PORT}:5001'
    volumes:
      - ./:/app/
      - /app/node_modules
    depends_on:
      - db

volumes:
  db_data:
