version: '3.8'

services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - api

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5000
    environment:
      DATABASE_HOST: '${DATABASE_HOST}'
      DATABASE_PORT: '${DATABASE_PORT}'
      DATABASE_USER: '${DATABASE_USER}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      DATABASE_NAME: '${DATABASE_NAME}'
    volumes:
      - ./:/app
    networks:
      - api
    depends_on:
      - db

networks:
  api:

volumes:
  db-data:
